// Code generated by Caisin. DO NOT EDIT.
// source: apps/novel/internal/data/ent/schema/client_error.go

package convert

import (
	"google.golang.org/protobuf/types/known/timestamppb"
	v1 "hope/api/novel/clienterror/v1"
	"hope/apps/novel/internal/data/ent"
)

func ClientErrorUpdateReq2Data(v *v1.ClientErrorUpdateReq) *ent.ClientError {
	if v == nil {
		return nil
	}
	return &ent.ClientError{
		ID:         v.Id,
		AppVersion: v.AppVersion,
		DeviceName: v.DeviceName,
		OsName:     v.OsName,
		ErrorInfo:  v.ErrorInfo,
	}
}

func ClientErrorData2UpdateReq(v *ent.ClientError) *v1.ClientErrorUpdateReq {
	if v == nil {
		return nil
	}
	return &v1.ClientErrorUpdateReq{
		Id:         v.ID,
		AppVersion: v.AppVersion,
		DeviceName: v.DeviceName,
		OsName:     v.OsName,
		ErrorInfo:  v.ErrorInfo,
	}
}

func ClientErrorCreateReq2Data(v *v1.ClientErrorCreateReq) *ent.ClientError {
	if v == nil {
		return nil
	}
	return &ent.ClientError{
		AppVersion: v.AppVersion,
		DeviceName: v.DeviceName,
		OsName:     v.OsName,
		ErrorInfo:  v.ErrorInfo,
	}
}

func ClientErrorData2CreateReq(v *ent.ClientError) *v1.ClientErrorCreateReq {
	if v == nil {
		return nil
	}
	return &v1.ClientErrorCreateReq{
		AppVersion: v.AppVersion,
		DeviceName: v.DeviceName,
		OsName:     v.OsName,
		ErrorInfo:  v.ErrorInfo,
	}
}

func ClientErrorReq2Data(v *v1.ClientErrorReq) *ent.ClientError {
	if v == nil {
		return nil
	}
	return &ent.ClientError{
		AppVersion: v.AppVersion,
		DeviceName: v.DeviceName,
		OsName:     v.OsName,
		ErrorInfo:  v.ErrorInfo,
	}
}

func ClientErrorData2Req(v *ent.ClientError) *v1.ClientErrorReq {
	if v == nil {
		return nil
	}
	return &v1.ClientErrorReq{
		AppVersion: v.AppVersion,
		DeviceName: v.DeviceName,
		OsName:     v.OsName,
		ErrorInfo:  v.ErrorInfo,
	}
}

func ClientErrorReply2Data(v *v1.ClientErrorReply) *ent.ClientError {
	if v == nil {
		return nil
	}
	return &ent.ClientError{
		ID:         v.Id,
		AppVersion: v.AppVersion,
		DeviceName: v.DeviceName,
		OsName:     v.OsName,
		ErrorInfo:  v.ErrorInfo,
		UserId:     v.UserId,
		CreatedAt:  v.CreatedAt.AsTime(),
		UpdatedAt:  v.UpdatedAt.AsTime(),
		CreateBy:   v.CreateBy,
		UpdateBy:   v.UpdateBy,
		TenantId:   v.TenantId,
	}
}

func ClientErrorData2Reply(v *ent.ClientError) *v1.ClientErrorReply {
	if v == nil {
		return nil
	}
	return &v1.ClientErrorReply{
		Id:         v.ID,
		AppVersion: v.AppVersion,
		DeviceName: v.DeviceName,
		OsName:     v.OsName,
		ErrorInfo:  v.ErrorInfo,
		UserId:     v.UserId,
		CreatedAt:  timestamppb.New(v.CreatedAt),
		UpdatedAt:  timestamppb.New(v.UpdatedAt),
		CreateBy:   v.CreateBy,
		UpdateBy:   v.UpdateBy,
		TenantId:   v.TenantId,
	}
}

func ClientErrorUpdateReply2Data(v *v1.ClientErrorUpdateReply) *ent.ClientError {
	if v == nil {
		return nil
	}
	return &ent.ClientError{
		ID:         v.Id,
		AppVersion: v.AppVersion,
		DeviceName: v.DeviceName,
		OsName:     v.OsName,
		ErrorInfo:  v.ErrorInfo,
	}
}

func ClientErrorData2UpdateReply(v *ent.ClientError) *v1.ClientErrorUpdateReply {
	if v == nil {
		return nil
	}
	return &v1.ClientErrorUpdateReply{
		Id:         v.ID,
		AppVersion: v.AppVersion,
		DeviceName: v.DeviceName,
		OsName:     v.OsName,
		ErrorInfo:  v.ErrorInfo,
	}
}

func ClientErrorCreateReply2Data(v *v1.ClientErrorCreateReply) *ent.ClientError {
	if v == nil {
		return nil
	}
	return &ent.ClientError{
		ID:         v.Id,
		AppVersion: v.AppVersion,
		DeviceName: v.DeviceName,
		OsName:     v.OsName,
		ErrorInfo:  v.ErrorInfo,
		UserId:     v.UserId,
		CreatedAt:  v.CreatedAt.AsTime(),
		UpdatedAt:  v.UpdatedAt.AsTime(),
		CreateBy:   v.CreateBy,
		UpdateBy:   v.UpdateBy,
		TenantId:   v.TenantId,
	}
}

func ClientErrorData2CreateReply(v *ent.ClientError) *v1.ClientErrorCreateReply {
	if v == nil {
		return nil
	}
	return &v1.ClientErrorCreateReply{
		Id:         v.ID,
		AppVersion: v.AppVersion,
		DeviceName: v.DeviceName,
		OsName:     v.OsName,
		ErrorInfo:  v.ErrorInfo,
		UserId:     v.UserId,
		CreatedAt:  timestamppb.New(v.CreatedAt),
		UpdatedAt:  timestamppb.New(v.UpdatedAt),
		CreateBy:   v.CreateBy,
		UpdateBy:   v.UpdateBy,
		TenantId:   v.TenantId,
	}
}
