// Code generated by Caisin. DO NOT EDIT.
// source: apps/novel/internal/data/ent/schema/user_msg.go

package convert

import (
	"google.golang.org/protobuf/types/known/timestamppb"
	v1 "hope/api/novel/usermsg/v1"
	"hope/apps/novel/internal/data/ent"
)

func UserMsgUpdateReq2Data(v *v1.UserMsgUpdateReq) *ent.UserMsg {
	if v == nil {
		return nil
	}
	return &ent.UserMsg{
		ID:     v.Id,
		UserId: v.UserId,
		MsgId:  v.MsgId,
	}
}

func UserMsgData2UpdateReq(v *ent.UserMsg) *v1.UserMsgUpdateReq {
	if v == nil {
		return nil
	}
	return &v1.UserMsgUpdateReq{
		Id:     v.ID,
		UserId: v.UserId,
		MsgId:  v.MsgId,
	}
}

func UserMsgCreateReq2Data(v *v1.UserMsgCreateReq) *ent.UserMsg {
	if v == nil {
		return nil
	}
	return &ent.UserMsg{
		UserId: v.UserId,
		MsgId:  v.MsgId,
	}
}

func UserMsgData2CreateReq(v *ent.UserMsg) *v1.UserMsgCreateReq {
	if v == nil {
		return nil
	}
	return &v1.UserMsgCreateReq{
		UserId: v.UserId,
		MsgId:  v.MsgId,
	}
}

func UserMsgReq2Data(v *v1.UserMsgReq) *ent.UserMsg {
	if v == nil {
		return nil
	}
	return &ent.UserMsg{
		UserId: v.UserId,
		MsgId:  v.MsgId,
	}
}

func UserMsgData2Req(v *ent.UserMsg) *v1.UserMsgReq {
	if v == nil {
		return nil
	}
	return &v1.UserMsgReq{
		UserId: v.UserId,
		MsgId:  v.MsgId,
	}
}

func UserMsgReply2Data(v *v1.UserMsgReply) *ent.UserMsg {
	if v == nil {
		return nil
	}
	return &ent.UserMsg{
		ID:        v.Id,
		UserId:    v.UserId,
		MsgId:     v.MsgId,
		IsRead:    v.IsRead,
		CreatedAt: v.CreatedAt.AsTime(),
		UpdatedAt: v.UpdatedAt.AsTime(),
		CreateBy:  v.CreateBy,
		UpdateBy:  v.UpdateBy,
		TenantId:  v.TenantId,
	}
}

func UserMsgData2Reply(v *ent.UserMsg) *v1.UserMsgReply {
	if v == nil {
		return nil
	}
	return &v1.UserMsgReply{
		Id:        v.ID,
		UserId:    v.UserId,
		MsgId:     v.MsgId,
		IsRead:    v.IsRead,
		CreatedAt: timestamppb.New(v.CreatedAt),
		UpdatedAt: timestamppb.New(v.UpdatedAt),
		CreateBy:  v.CreateBy,
		UpdateBy:  v.UpdateBy,
		TenantId:  v.TenantId,
	}
}

func UserMsgUpdateReply2Data(v *v1.UserMsgUpdateReply) *ent.UserMsg {
	if v == nil {
		return nil
	}
	return &ent.UserMsg{
		ID:     v.Id,
		UserId: v.UserId,
		MsgId:  v.MsgId,
	}
}

func UserMsgData2UpdateReply(v *ent.UserMsg) *v1.UserMsgUpdateReply {
	if v == nil {
		return nil
	}
	return &v1.UserMsgUpdateReply{
		Id:     v.ID,
		UserId: v.UserId,
		MsgId:  v.MsgId,
	}
}

func UserMsgCreateReply2Data(v *v1.UserMsgCreateReply) *ent.UserMsg {
	if v == nil {
		return nil
	}
	return &ent.UserMsg{
		ID:        v.Id,
		UserId:    v.UserId,
		MsgId:     v.MsgId,
		IsRead:    v.IsRead,
		CreatedAt: v.CreatedAt.AsTime(),
		UpdatedAt: v.UpdatedAt.AsTime(),
		CreateBy:  v.CreateBy,
		UpdateBy:  v.UpdateBy,
		TenantId:  v.TenantId,
	}
}

func UserMsgData2CreateReply(v *ent.UserMsg) *v1.UserMsgCreateReply {
	if v == nil {
		return nil
	}
	return &v1.UserMsgCreateReply{
		Id:        v.ID,
		UserId:    v.UserId,
		MsgId:     v.MsgId,
		IsRead:    v.IsRead,
		CreatedAt: timestamppb.New(v.CreatedAt),
		UpdatedAt: timestamppb.New(v.UpdatedAt),
		CreateBy:  v.CreateBy,
		UpdateBy:  v.UpdateBy,
		TenantId:  v.TenantId,
	}
}
