// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"hope/apps/param/internal/data/ent/noveltag"
	"hope/apps/param/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NovelTagDelete is the builder for deleting a NovelTag entity.
type NovelTagDelete struct {
	config
	hooks    []Hook
	mutation *NovelTagMutation
}

// Where appends a list predicates to the NovelTagDelete builder.
func (ntd *NovelTagDelete) Where(ps ...predicate.NovelTag) *NovelTagDelete {
	ntd.mutation.Where(ps...)
	return ntd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ntd *NovelTagDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ntd.hooks) == 0 {
		affected, err = ntd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NovelTagMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ntd.mutation = mutation
			affected, err = ntd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ntd.hooks) - 1; i >= 0; i-- {
			if ntd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ntd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ntd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ntd *NovelTagDelete) ExecX(ctx context.Context) int {
	n, err := ntd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ntd *NovelTagDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: noveltag.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: noveltag.FieldID,
			},
		},
	}
	if ps := ntd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ntd.driver, _spec)
}

// NovelTagDeleteOne is the builder for deleting a single NovelTag entity.
type NovelTagDeleteOne struct {
	ntd *NovelTagDelete
}

// Exec executes the deletion query.
func (ntdo *NovelTagDeleteOne) Exec(ctx context.Context) error {
	n, err := ntdo.ntd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{noveltag.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ntdo *NovelTagDeleteOne) ExecX(ctx context.Context) {
	ntdo.ntd.ExecX(ctx)
}
